### PR TITLE
feat: add limit to pause after a quantity of searchs

### PR DESCRIPTION
**Pull request by marilozgz**
Add attributes to the config and include the necessary steps to pause the search when the chosen number and the specified amount of time are reached

### CODE REVIEW

**Comment by TheNetsky** [comment]
I will not merge this. Feel free to use this on your own fork.

**Comment by marilozgz** [comment]
Ok thanks, just trying to collaborate to help with one of the biggest actual problems.

**Comment by TheNetsky** [comment]
It's only an issue for those in affected areas. When it comes to that, I'll maybe implement a fix. However looking at the PR you're changing a bunch of stuff regarding eslint and formatting. Which I don't understand why you're doing those.

**Comment by marilozgz** [comment]
Sorry about the eslint, was late and I didn't check . anyway i will keep in my fork the changes for that issue, really common for a lot of people.

**Pull request closed without merging**
