### PR TITLE
Support new quest to get points

### PR DESCRIPTION
**Pull request by hmcdat**
I added two quest including Daily check-in reward and Read To Earn, supported all regions.
Tell me if any regions don't support.

### CODE REVIEW

**Comment by TheNetsky** [comment]
Great work, I'll take a look at it soon!

**Comment by hmcdat** [comment]
I recommend you to set the option searchSettings.useGeoLocaleQueries = true in the config.json.
If it isn't working, can you show me your runtime console?

**Comment by TheNetsky** [comment]
I'm pretty sure GoogleTrends does not work, see https://github.com/TheNetsky/Microsoft-Rewards-Script/issues/136

**Comment by TheNetsky** [comment]
I think unless you're using a VPN it won't work, I assume, no matter where you set the geoLocale to.

**Comment by hmcdat** [comment]
Can you change the changelog to the current title? I think it needs a short and specific detail.

**Comment by TheNetsky** [comment]
> Can you change the changelog to the current title? I think it needs a short and specific detail.

Done

**Comment by mgrimace** [comment]
Nice work! FYI anyone using docker will likely need to stop, remove the container, and rebuild the container using `docker compose up -d --build' to integrate the new config options. I don't believe `docker compose up -d` alone will grab the new source config.

For example:
```bash
docker stop netsky && docker rm netsky && docker system prune -a -f
docker compose up -d --build
```

**Comment by TheNetsky** [comment]
Open up a issue instead, easier

**Pull request merged**
