### PR TITLE
Increasing timeout on login and go-home

### PR DESCRIPTION
**Pull request by serzak51**
The script will wait 60 seconds for the page to load instand of 30 seconds. For really slow connection a 2 minutes timeout on the go-home might be necessary (for the login 60 seconds seems to never produce any error)
Also does anywone know how i remove the first commit? When testing i modified it directly on the compiled code, tried uploading, but it wasn't the same format, and now deleting the file doesn't work, and i can't find a button to revert the commit

### CODE REVIEW

**Comment by serzak51** [comment]
Nevermind i found it, i just didn't commit the delete action

**Comment by TheNetsky** [comment]
I've already tinkered with some timeout in a new upcoming version, however not being able to load a page in 30 seconds (default timeout) is quite something. Searches must be taking forever. So I don't really think increasing the timeout is really a solution to something like that. I think it would be better to get a VPS or alike that has some better connection.

**Comment by Oussema-Hakim** [comment]
increasing timeout actually helped me, obviously when i search the page doesn't take that long but for some reason when i use multiple clusters (i m using 4 ) the 30s timeout is guaranteed to trigger at least once , not sure why but i tried using one cluster and it didn't happen

**Comment by serzak51** [comment]
I don't even think it's actually user related. Often yeah 30 seconds is overkill, but sometimes for some reason it takes ages to load pictures, not sure why. And on one of my connection it actually was triggered every time. It was wireless fiber, so maybe instand of loading the images in parrellel, microsoft decided to load them sequentially, meaning that high ping increase the load time? Just a theory, i'm not even sure you can do that

**Pull request closed without merging**
